### ISSUE TITLE
Use FileModel().open() as Context Manager

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/stemserver#11]
We might need to use the file model [open function](https://github.com/OpenChemistry/stemserver/blob/7e4f6e46c68faf93fa7fa1a35fef4bc7e7dea90e/girder/stemserver_plugin/models/stemimage.py#L101) as a [context manager](https://github.com/girder/girder/blob/326d89f36c1f9b394b0a6e1656c305fca4aeadeb/girder/models/file.py#L460) to ensure that the file actually gets closed.

I may work on this one after #8 finishes since some of the file opening code is edited there.

**Comment by cjh1** [comment]
Absolutely!
