### ISSUE TITLE
Renaming `detectorDimensions` endpoint to `shape` ?

### ISSUE THREAD

**Issue by alesgenova** [OpenChemistry/stemserver#17]
For the bright and dark field we have these two endpoints to determine the size of the images:
`/stem_images/{id}/bright/shape`
`/stem_images/{id}/dark/shape`

For the frames however, we use a different naming convention:
`/stem_images/{id}/frames/detectorDimensions`

Should we rename it to
`/stem_images/{id}/frames/shape` ?

**Comment by cryos** [comment]
I think using shape for all seems reasonable.
