### ISSUE TITLE
Unify local files with those held in an assetstore 

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/stemserver#9]
We currently have two code paths one for local file and one for those held in an assetstore. I think we can unify them. The filesystem assetstore has a function to [import](https://github.com/girder/girder/blob/master/girder/utility/filesystem_assetstore_adapter.py#L336) existing files into the assetstore, we can do this as part of the creation logic add store the file id, as which point all our stem images will have a file id so we can treat them the same.

**Comment by psavery** [comment]
:+1: Sounds like a good idea to me.
